name: Pull Request

on: pull_request

jobs:
  tests-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Proto Tests
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test
      - name: Unit Tests
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit
      - name: Lint
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
