name: Pull Request

on: pull_request

jobs:
  tests-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Unit Tests
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit
      - name: Lint
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
  test-proto-changes:
    runs-on: ubuntu-latest
    name: Test Proto Changes
    container:
      image: lyft/protocgenerator:8167e11d3b3439373c2f033080a4b550078884a2
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Service
        run: python3 /usr/local/bin/entrypoint.py -i ./protos -d protos/flyteidl/service --with_gateway -l go --go_source_relative
